#!/usr/bin/env bash
# deploy.sh — deploy tRäning pipeline to kailash
#
# Usage:
#   deploy.sh code      Pull code, install deps, restart services
#   deploy.sh secrets   SCP credentials to kailash
#   deploy.sh tokens    SCP Garmin auth tokens to kailash
#   deploy.sh status    Show service status and recent logs
#   deploy.sh check     Run `traning doctor` against kailash
#   deploy.sh all       code + secrets + tokens + enable services

set -euo pipefail

REMOTE="kailash"
REMOTE_CODE="~/dev/traning"
REMOTE_DATA="~/dokument/traning-data"
DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/../../../../" && pwd)"

# Resolve local data dir from .Renviron or env
LOCAL_DATA="${TRANING_DATA:-$(grep '^TRANING_DATA=' "$REPO_ROOT/.Renviron" 2>/dev/null | cut -d= -f2 || echo "$HOME/Documents/traning-data")}"

_info()  { echo "==> $*"; }
_warn()  { echo "WARN: $*" >&2; }

cmd_code() {
    _info "Pulling latest code on $REMOTE ..."
    ssh "$REMOTE" "cd $REMOTE_CODE && git pull --ff-only"

    _info "Installing Python dependencies ..."
    ssh "$REMOTE" "cd $REMOTE_CODE && \
        (test -d python/.venv || python3 -m venv python/.venv) && \
        python/.venv/bin/pip install --quiet --upgrade pip && \
        python/.venv/bin/pip install --quiet -e ."

    _info "Installing R dependencies ..."
    ssh "$REMOTE" "cd $REMOTE_CODE && bash scripts/install_r_deps.sh"

    _info "Copying systemd units ..."
    ssh "$REMOTE" "sudo cp \
        $REMOTE_CODE/python/traning_cli/server/deploy/traning-*.service \
        $REMOTE_CODE/python/traning_cli/server/deploy/traning-*.timer \
        /etc/systemd/system/ && \
        sudo systemctl daemon-reload"

    _info "Installing pacman post-upgrade hook ..."
    ssh "$REMOTE" "sudo install -m 644 -o root -g root \
        $REMOTE_CODE/python/traning_cli/server/deploy/traning-r-postupgrade.hook \
        /etc/pacman.d/hooks/"

    _info "Restarting traning-receiver, traning-shiny, traning-vayu ..."
    ssh "$REMOTE" "sudo systemctl restart traning-receiver.service && \
        sudo systemctl restart traning-shiny.service && \
        sudo systemctl restart traning-vayu.service"

    _info "Code deployed"
}

cmd_secrets() {
    local env_local="$DEPLOY_DIR/traning-env.local"
    if [ ! -f "$env_local" ]; then
        _warn "Missing $env_local — copy traning-env.example and fill in values"
        exit 1
    fi

    _info "Copying env file to $REMOTE:/etc/traning/env ..."
    scp "$env_local" "$REMOTE:/tmp/traning-env"
    ssh "$REMOTE" "sudo mkdir -p /etc/traning && \
        sudo mv /tmp/traning-env /etc/traning/env && \
        sudo chmod 600 /etc/traning/env"

    # Create .Renviron on kailash pointing to the env file
    _info "Creating .Renviron on $REMOTE (sources /etc/traning/env) ..."
    ssh "$REMOTE" "cat > $REMOTE_CODE/.Renviron <<'RENV'
# Auto-generated by deploy.sh — sources server env
TRANING_DATA=/home/krisse/dokument/traning-data
TRANING_OPEN=false
R_LIBS_USER=~/R/library
LANG=sv_SE.utf8
RENV"

    _info "Secrets deployed"
}

cmd_tokens() {
    local token_dir="$LOCAL_DATA/.garmin_tokens"
    if [ ! -d "$token_dir" ]; then
        _warn "No .garmin_tokens/ found in $LOCAL_DATA"
        _warn "Run: traning fetch garmin --reauth --dry-run"
        exit 1
    fi

    _info "Copying Garmin tokens to $REMOTE:$REMOTE_DATA/ ..."
    scp -r "$token_dir" "$REMOTE:$REMOTE_DATA/"

    _info "Tokens deployed"
}

cmd_status() {
    _info "Service status on $REMOTE:"
    ssh "$REMOTE" "
        echo '--- traning-receiver ---'
        systemctl status traning-receiver.service --no-pager 2>&1 || true
        echo ''
        echo '--- traning-shiny ---'
        systemctl status traning-shiny.service --no-pager 2>&1 || true
        echo ''
        echo '--- timers ---'
        systemctl list-timers 'traning-*' --no-pager 2>&1 || true
        echo ''
        echo '--- recent receiver logs ---'
        journalctl -u traning-receiver --since '1h ago' --no-pager -n 20 2>&1 || true
        echo ''
        echo '--- recent shiny logs ---'
        journalctl -u traning-shiny --since '1h ago' --no-pager -n 10 2>&1 || true
        echo ''
        echo '--- recent garmin logs ---'
        journalctl -u traning-garmin --since '24h ago' --no-pager -n 10 2>&1 || true
    "
}

cmd_check() {
    _info "Running traning doctor on $REMOTE ..."
    # Mirror the systemd unit's runtime environment (env file, R lib
    # path, working directory) so that .libPaths() and config paths
    # resolve identically — otherwise an unprivileged ssh invocation
    # could read different libraries than the daily timer and report
    # "healthy" while production is broken. set -e + ssh propagate
    # exit code; doctor exits 1 on any check fail.
    ssh "$REMOTE" "set -a && . /etc/traning/env && set +a && \
        export R_LIBS_USER=/home/krisse/R/library && \
        cd /home/krisse/dev/traning && \
        python/.venv/bin/traning doctor run"
}

cmd_all() {
    cmd_code
    cmd_secrets
    cmd_tokens

    _info "Enabling services and timers ..."
    ssh "$REMOTE" "
        sudo systemctl enable --now traning-receiver.service
        sudo systemctl enable --now traning-shiny.service
        sudo systemctl enable --now traning-garmin.timer
        sudo systemctl enable --now traning-push.timer
        sudo systemctl enable --now traning-daysummary.timer
        sudo systemctl enable --now traning-doctor.timer
    "

    cmd_status
}

# Main
case "${1:-}" in
    code)    cmd_code ;;
    secrets) cmd_secrets ;;
    tokens)  cmd_tokens ;;
    status)  cmd_status ;;
    check)   cmd_check ;;
    all)     cmd_all ;;
    *)
        echo "Usage: deploy.sh {code|secrets|tokens|status|check|all}"
        echo ""
        echo "  code      Pull code, install deps, restart services"
        echo "  secrets   SCP credentials (traning-env.local) to kailash"
        echo "  tokens    SCP Garmin auth tokens to kailash"
        echo "  status    Show service status and recent logs"
        echo "  check     Run \`traning doctor\` against kailash"
        echo "  all       code + secrets + tokens + enable all services"
        exit 1
        ;;
esac
